# Configuration file used by the cloud-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: merge
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  # Important, committing to the .github/workflows folder 
  # require the user to have "workflow" scope on the token
  # https://github.com/octokit/rest.js/issues/368
  - files:
      - .github/release.yml
      - from: .github/ISSUE_TEMPLATE
        to: .github/ISSUE_TEMPLATE
        exclude:
          - '**/custom_*/*'
      - from: .github/ISSUE_TEMPLATE/custom_cloud
        to: .github/ISSUE_TEMPLATE
    repositories:
      # An updated version of this list can be obtained by running this 
      # workflow: https://github.com/Jahia/.github/actions/workflows/delivery-list-cloud-repos.yml
      # IMPORTANT: The following repositories should not be synced
      # from the list based on topics, make sure to remove them if present:
      # - Jahia/.github => This is the current repository
      # - Jahia/jahia => This is a clone of jahia-private

      # To uncomment before migration
#      - Jahia/cloud-core-ansible@main
#      - Jahia/cloud-core-ara@main
#      - Jahia/cloud-core-infrastructure@main
#      - Jahia/cloud-core-monitoring@main
#      - Jahia/cloud-core-routing@main
#      - Jahia/cloud-core-terraform-registry@main
#      - Jahia/cloud-core-vault@main
#      - Jahia/cloud-ec-infra@main
#      - Jahia/cloud-fallback-vpn@main
#      - Jahia/cloud-guru@main
      - Jahia/cloud-issues@main
#      - Jahia/cloud-nginx4github@main
#      - Jahia/cloud-ops-dashboard@main
#      - Jahia/cloud-ops-dashboard-k8s@main
#      - Jahia/cloud-papi@main
#      - Jahia/cloud-utils@main
#      - Jahia/docker-autobackup@main
#      - Jahia/docker-jahia-cloud@main
#      - Jahia/docker-papi@main
#      - Jahia/jahiastic-jahia@main
#      - Jahia/jahiastic-jcustomer@main
#      - Jahia/jelastic-packages@main
#      - Jahia/paas-ansible@main
#      - Jahia/paas-build-rpms@main
#      - Jahia/paas-monitoring@main
#      - Jahia/papi-k8s@main
#      - Jahia/papi-terraform-provider@main
#      - Jahia/pylastic@main
