# Configuration file used by the product-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: squash
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  - files:
      - .github/release.yml
      - .github/workflows/delivery-issue-chores.yml
      # - .github/workflows/delivery-pr-chores.yml
      # - .github/workflows/delivery-repo-chores.yml
    repositories:
      - jahia/sandbox@main
