# Configuration file used by the product-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: squash
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  # Important, committing to the .github/workflows folder 
  # require the user to have "workflow" scope on the token
  # https://github.com/octokit/rest.js/issues/368
  - files:
      - .github/release.yml
      - from: .github/ISSUE_TEMPLATE
        to: .github/ISSUE_TEMPLATE
        exclude:
          - 'product'        
      - from: .github/ISSUE_TEMPLATE/product
        to: .github/ISSUE_TEMPLATE        
      # Skipping the PR chores workflow until right before the migration to GitHub issues
      # - .github/workflows/delivery-pr-chores.yml
    repositories:
      # An updated version of this list can be obtained by running this 
      # workflow: https://github.com/Jahia/.github/actions/workflows/delivery-list-repos.yml
      # IMPORTANT: The following repositories should not be synced
      # from the list based on topics, make sure to remove them:
      # - Jahia/.github => This is the current repository
      # - Jahia/jahia => This is a clone of jahia-private

      # To uncomment before migration
      # - Jahia/advanced-visibility@master
      # - Jahia/app-shell@master
      # - Jahia/asset-webpack-example@main
      # - Jahia/assets@master
      # - Jahia/atmosphere@master
      # - Jahia/augmented-search@master
      # - Jahia/augmented-search-custom-configuration@master
      # - Jahia/augmented-search-package@master
      # - Jahia/augmented-search-taglib@master
      # - Jahia/augmented-search-ui@master
      # - Jahia/automated-tagging@master
      # - Jahia/bootstrap4@master
      # - Jahia/brute-force-login-protection@master
      # - Jahia/cas-authentication-valve@master
      # - Jahia/channels@master
      # - Jahia/cimg-mvn-cache@main
      # - Jahia/ckeditor@master
      # - Jahia/ckeditor-dev@master
      # - Jahia/clamav-filter@main
      # - Jahia/cloud-support-token-authentication-valve@main
      # - Jahia/cloudimage@main
      # - Jahia/cloudinary-picker@main
      # - Jahia/clustering@main
      # - Jahia/cmis-provider@master
      # - Jahia/contact@master
      # - Jahia/content-editor@master
      # - Jahia/content-reports@master
      # - Jahia/content-security-policy@master
      # - Jahia/contentRetrieval@master
      # - Jahia/contentsquare-accessibility-plugin@main
      # - Jahia/copy-to-other-languages@main
      # - Jahia/core-perf-test@master
      # - Jahia/core-perf-test-JMeter-WebSocketSampler@master
      # - Jahia/core-perf-test-terraform@main
      # - Jahia/dalim-provider@master
      # - Jahia/database-connector@master
      # - Jahia/default@master
      # - Jahia/default-skins@master
      # - Jahia/deleted-issues@main
      # - Jahia/df-tests-api@master
      # - Jahia/digitall@master
      # - Jahia/digitall-package@master
      # - Jahia/directive-filter@master
      # - Jahia/distributed-sessions@master
      # - Jahia/docConverter@master
      # - Jahia/docker-elasticsearch@main
      # - Jahia/docker-openldap@master
      # - Jahia/document-management@master
      # - Jahia/download-helper@master
      # - Jahia/drools@master
      # - Jahia/dummy-csrf-test-module@master
      # - Jahia/dx-tests-specs@master
      # - Jahia/ehcache@master
      # - Jahia/el-spec@master
      # - Jahia/elasticsearch-connector@master
      # - Jahia/estool@main
      # - Jahia/event@master
      # - Jahia/external-provider@master
      # - Jahia/external-provider-users-groups@master
      # - Jahia/facets@master
      # - Jahia/faq@master
      # - Jahia/favicon-manager@master
      # - Jahia/felix-dev@master
      # - Jahia/font-awesome@master
      # - Jahia/forcePublishAll@main
      # - Jahia/forms-core@master
      # - Jahia/forms-core-tests@master
      # - Jahia/forms-elasticsearch-storage@master
      # - Jahia/forms-elasticsearch-storage-tests@master
      # - Jahia/forms-extended-inputs@master
      # - Jahia/forms-nocss-theme@master
      # - Jahia/forms-package@master
      # - Jahia/forms-prefill@master
      # - Jahia/forms-snippets-extension@master
      # - Jahia/full-read-only-notifier@master
      # - Jahia/function-score-examples@master
      # - Jahia/gemini.blueprint@master
      # - Jahia/github-actions-runners@v5.17.0
      # - Jahia/graphql-core@master
      # - Jahia/graphql-java-servlet@master
      # - Jahia/html-filtering@main
      # - Jahia/izpack@4.3
      # - Jahia/jaas-authentication-valve@master
      # - Jahia/jackrabbit@trunk
      # - Jahia/jahia-administration@master
      # - Jahia/jahia-authentication@master
      # - Jahia/jahia-base-demo-components@master
      # - Jahia/jahia-base-demo-core@master
      # - Jahia/jahia-base-demo-templates@master
      # - Jahia/jahia-category-manager@master
      # - Jahia/jahia-cloud-modules@main
      # - Jahia/jahia-commons@master
      # - Jahia/jahia-configuration@master
      # - Jahia/jahia-csrf-guard@master
      # - Jahia/jahia-cypress@main
      # - Jahia/jahia-dashboard@master
      # - Jahia/jahia-dashboard-docs@master
      # - Jahia/jahia-dev-private@master
      # - Jahia/jahia-developer-tools@master
      # - Jahia/jahia-ee@master
      # - Jahia/Jahia-MF-Integ-Test-Site@master
      # - Jahia/jahia-modules-action@main
      # - Jahia/jahia-oauth@master
      # - Jahia/jahia-pack@master
      # - Jahia/jahia-pack-private@master
      # - Jahia/jahia-page-composer@master
      # - Jahia/jahia-private@master
      # - Jahia/jahia-qa@master
      # - Jahia/jahia-qa-data@main
      # - Jahia/jahia-reporter@main
      # - Jahia/jahia-repository-explorer@master
      # - Jahia/jahia-security-issue-workflow@main
      # - Jahia/jahia-ui-root@master
      # - Jahia/jahia-user-entries@master
      # - Jahia/jahia-user-feedbacks@main
      # - Jahia/JahiApp-Newsletter@master
      # - Jahia/JahiaReleaseTool@master
      # - Jahia/java-ts-bind@master
      # - Jahia/javascript-components@master
      # - Jahia/javascript-modules@main
      # - Jahia/jcifs-authentication-valve@master
      # - Jahia/jcontent@master
      # - Jahia/jcr-account-creation-notification@master
      # - Jahia/jcr-auth-provider@master
      # - Jahia/jcr-webdav@master
      # - Jahia/jcrestapi@master
      # - Jahia/jcustomer@master
      # - Jahia/jcustomer-custom-event-checker@master
      # - Jahia/jcustomer-perf@main
      # - Jahia/jexperience@master
      # - Jahia/jexperience-auth-data-mapper@master
      # - Jahia/jexperience-condition-example@master
      # - Jahia/jexperience-dashboards@main
      # - Jahia/jexperience-forms-bridge@master
      # - Jahia/jquery@master
      # - Jahia/karaf-cellar@cellar-4.1.3-jahia-fixes
      # - Jahia/keepicker@main
      # - Jahia/keymaker@master
      # - Jahia/kibana-dashboards-provider@master
      # - Jahia/ldap-oauth-provider@master
      # - Jahia/LDAP-provider@master
      # - Jahia/legacy-default-components@main
      # - Jahia/license-tools@master
      # - Jahia/linkchecker@master
      # - Jahia/lucene-solr@master
      # - Jahia/luxe-jahia-demo@main
      # - Jahia/luxe-prepackaged-website@main
      # - Jahia/macros@master
      # - Jahia/maven-archetypes@master
      # - Jahia/maven-release@master
      # - Jahia/module-manager@master
      # - Jahia/moonstone@develop
      # - Jahia/mvel@master
      # - Jahia/news@master
      # - Jahia/news-qamf@master
      # - Jahia/npm-create-module@main
      # - Jahia/npm-jsx-templates-web-blue@main
      # - Jahia/npm-solid-react-templateset-example@master
      # - Jahia/npm-templates-web-blue@main
      # - Jahia/open-source@master
      # - Jahia/opencode@main
      # - Jahia/org.ops4j.pax.web@main
      # - Jahia/OSGi-modules-samples@master
      # - Jahia/personal-api-tokens@main
      # - Jahia/prevent-cross-sites-access@main
      # - Jahia/preview-cloud@main
      # - Jahia/preview-env@master
      # - Jahia/privateappstore@master
      # - Jahia/profile@master
      # - Jahia/provisioning-tutorials@main
      # - Jahia/qa-mf-common-utils@master
      # - Jahia/qa-mf-referrer-site@master
      # - Jahia/qa-mf-selenium@master
      # - Jahia/qa-mf-unomi-api@master
      # - Jahia/qa-mf-unomi-tracker-site@master
      # - Jahia/QA-Modules@master
      # - Jahia/remotepublish@master
      # - Jahia/richtext-ckeditor5@main
      # - Jahia/robots@master
      # - Jahia/rolesmanager@master
      # - Jahia/root-login-notification@master
      # - Jahia/sam-cluster-revisions-check@main
      # - Jahia/saml-authentication-valve@master
      - Jahia/sandbox@main
      # - Jahia/scheduled-publication-workflow@main
      # - Jahia/sdk-jahia@master
      # - Jahia/sdl-generator-tools@master
      # - Jahia/sdl-generator-tools-tests@master
      # - Jahia/search@master
      # - Jahia/search-ui-jahia-connector@master
      # - Jahia/security-filter-tools@master
      # - Jahia/selenium@master
      # - Jahia/semj4jahia@main
      # - Jahia/seo@master
      # - Jahia/server-availability-manager@main
      # - Jahia/serverSettings@master
      # - Jahia/serverSettings-ee@master
      # - Jahia/site-settings-publication@master
      # - Jahia/site-settings-seo@master
      # - Jahia/siteimprove-connector@master
      # - Jahia/sitemap@master
      # - Jahia/sitemap-legacy-html@main
      # - Jahia/siteSettings@master
      # - Jahia/skins@master
      # - Jahia/spnego-authentication-valve@master
      # - Jahia/spring-framework@main
      # - Jahia/support-token-authentication-valve@master
      # - Jahia/tabularList@master
      # - Jahia/tags@master
      # - Jahia/tasks@master
      # - Jahia/templates-system@master
      # - Jahia/tomcat-log-provider@master
      # - Jahia/tools@master
      # - Jahia/tools-ee@master
      # - Jahia/translation-deepl@main
      # - Jahia/translation-globallink@master
      # - Jahia/trivy-db@main
      # - Jahia/update-manager@master
      # - Jahia/user-cleanup-tool@main
      # - Jahia/userDashboard@master
      # - Jahia/versions-cleaner@master
      # - Jahia/visibility@master
      # - Jahia/what-is-my-public-server-ip@master
      # - Jahia/workato-unomi-connector@master
      # - Jahia/workflow-extender@main
      # - Jahia/workflow-tasks-cleaner@master