# Configuration file used by the product-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: squash
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  # Important, committing to the .github/workflows folder 
  # require the user to have "workflow" scope on the token
  # https://github.com/octokit/rest.js/issues/368
  - files:
      - .github/release.yml
      - from: .github/ISSUE_TEMPLATE
        to: .github/ISSUE_TEMPLATE
        exclude:
          - '**/custom_*/*'        
      - from: .github/ISSUE_TEMPLATE/custom_product
        to: .github/ISSUE_TEMPLATE
      - .github/workflows/delivery-issue-chores.yml
      - .github/workflows/delivery-pr-chores.yml
    delete_files:
      - .github/ISSUE_TEMPLATE/cloud-change-request.yml
    repositories:
      # An updated version of this list can be obtained by running this 
      # workflow: https://github.com/Jahia/.github/actions/workflows/delivery-list-product-repos.yml
      # IMPORTANT: The following repositories should not be synced
      # from the list based on topics, make sure to remove them:
      # - Jahia/.github => This is the current repository
      # - Jahia/jahia => This is a clone of jahia-private
      - Jahia/advanced-visibility@master
      - Jahia/app-shell@master
      - Jahia/asset-webpack-example@main
      - Jahia/assets@master
      - Jahia/atmosphere@master
      - Jahia/augmented-search@master
      - Jahia/augmented-search-custom-configuration@master
      - Jahia/automated-tagging@master
      - Jahia/cas-authentication-valve@master
      - Jahia/cimg-mvn-cache@main
      - Jahia/ckeditor@master
      - Jahia/ckeditor-dev@master
      - Jahia/client-cache-control@main
      - Jahia/cloudimage@main
      - Jahia/clustering@main
      - Jahia/cmis-provider@master
      - Jahia/content-editor@master
      - Jahia/content-reports@master
      - Jahia/content-security-policy@master
      - Jahia/contentRetrieval@master
      - Jahia/copy-to-other-languages@main
      - Jahia/core-perf-test-JMeter-WebSocketSampler@master
      - Jahia/core-perf-test-terraform@main
      - Jahia/database-connector@master
      - Jahia/default@master
      - Jahia/deleted-issues@main
      - Jahia/df-tests-api@master
      - Jahia/directive-filter@master
      - Jahia/distributed-sessions@master
      - Jahia/docker-elasticsearch@main
      - Jahia/docker-openldap@master
      - Jahia/dummy-csrf-test-module@master
      - Jahia/ehcache@master
      - Jahia/el-spec@master
      - Jahia/elasticsearch-connector@master
      - Jahia/estool@main
      - Jahia/external-provider@master
      - Jahia/external-provider-users-groups@master
      - Jahia/facets@master
      - Jahia/forms-core@master
      - Jahia/forms-core-tests@master
      - Jahia/forms-extended-inputs@master
      - Jahia/forms-nocss-theme@master
      - Jahia/forms-package@master
      - Jahia/karaf-cellar@cellar-4.1.3-jahia-fixes
      - Jahia/keepicker@main
      - Jahia/LDAP-provider@master
      - Jahia/legacy-default-components@main
      - Jahia/linkchecker@master
      - Jahia/lucene-solr@master
      - Jahia/luxe-jahia-demo@main
      - Jahia/luxe-prepackaged-website@main
      - Jahia/macros@master
      - Jahia/maven-archetypes@master
      - Jahia/maven-release@master
      - Jahia/module-manager@master
      - Jahia/mvel@master
      - Jahia/news-qamf@master
      - Jahia/npm-jsx-templates-web-blue@main
      - Jahia/npm-solid-react-templateset-example@master
      - Jahia/npm-templates-web-blue@main
      - Jahia/open-source@master
      - Jahia/opencode@main
      - Jahia/org.ops4j.pax.web@main
      - Jahia/personal-api-tokens@main
      - Jahia/pm@main
      - Jahia/preview-cloud@main
      - Jahia/profile@master
      - Jahia/provisioning-tutorials@main
      - Jahia/qa-mf-common-utils@master
      - Jahia/qa-mf-referrer-site@master
      - Jahia/qa-mf-selenium@master
      - Jahia/qa-mf-unomi-api@master
      - Jahia/qa-mf-unomi-tracker-site@master
      - Jahia/QA-Modules@master
      - Jahia/remotepublish@master
      - Jahia/richtext-ckeditor5@main
      - Jahia/robots@master
      - Jahia/rolesmanager@master
      - Jahia/saml-authentication-valve@master
      - Jahia/search@master
      - Jahia/seo@master
      - Jahia/server-availability-manager@main
      - Jahia/serverSettings@master
      - Jahia/serverSettings-ee@master
      - Jahia/site-settings-publication@master
      - Jahia/site-settings-seo@master
      - Jahia/siteimprove-connector@master
      - Jahia/sitemap@master
      - Jahia/siteSettings@master
      - Jahia/skins@master
      - Jahia/spnego-authentication-valve@master
      - Jahia/spring-framework@main
      - Jahia/static-assets-custom@main
      - Jahia/tags@master
      - Jahia/tasks@master
      - Jahia/templates-system@master
      - Jahia/tools@master
      - Jahia/tools-ee@master
      - Jahia/translation-globallink@master
      - Jahia/trivy-db@main
      - Jahia/urlrewritefilter@main
      - Jahia/userDashboard@master
      - Jahia/visibility@master
      - Jahia/workflow-extender@main
