# Configuration file used by the product-file-sync.yml workflow
settings:
  pull_request:
    title: 'chore: sync files with `<%- repository %>` [skip ci]'
    labels:
      - chore
    merge: 
      mode: admin
      strategy: squash
      delete_branch: true      
  commit: 
    format: '<%- prefix %>: <%- subject %>'
    prefix: 'chore'
    subject: 'sync files with `<%- repository %>` [skip ci]'
patterns:
  # Important, committing to the .github/workflows folder 
  # require the user to have "workflow" scope on the token
  # https://github.com/octokit/rest.js/issues/368
  - files:
      - .github/release.yml
      - from: .github/ISSUE_TEMPLATE
        to: .github/ISSUE_TEMPLATE
        exclude:
          - '**/custom_*/*'        
      - from: .github/ISSUE_TEMPLATE/custom_product
        to: .github/ISSUE_TEMPLATE
      - .github/workflows/delivery-issue-chores.yml
      - .github/workflows/delivery-pr-chores.yml
      - .github/workflows/docs-academy-update.yml
      - .github/workflows/docs-academy-publish.yml
      - .github/workflows/chachalog-comment-pr.yml
      - .github/workflows/chachalog-prepare-changelog.yml
      - .github/instructions/changelog.instructions.md
    delete_files:
      - .github/ISSUE_TEMPLATE/cloud-change-request.yml
    repositories:
      # An updated version of this list can be obtained by running this 
      # workflow: https://github.com/Jahia/.github/actions/workflows/delivery-list-product-repos.yml
      # IMPORTANT: The following repositories should not be synced
      # from the list based on topics, make sure to remove them:
      # - Jahia/.github => This is the current repository
      # - Jahia/jahia => This is a clone of jahia-private
      # - Jahia/pm => The repo used by PM for their internal issues
      # Though not supported, the following repos should also be present in the list:
      - Jahia/formidable@main
      - Jahia/request-safety-patch@main
      - Jahia/app-shell@main
      - Jahia/asset-webpack-example@main
      - Jahia/assets@main
      - Jahia/atmosphere@main
      - Jahia/augmented-search@main
      - Jahia/augmented-search-custom-configuration@main
      - Jahia/augmented-search-package@main
      - Jahia/augmented-search-ui@main
      - Jahia/automated-tagging@main
      - Jahia/cas-authentication-valve@main
      - Jahia/cimg-mvn-cache@main
      - Jahia/ckeditor@main
      - Jahia/ckeditor-dev@main
      - Jahia/cla-assistant@main
      - Jahia/client-cache-control@main
      - Jahia/cloudimage@main
      - Jahia/clustering@main
      - Jahia/cmis-provider@main
      - Jahia/content-editor@main
      - Jahia/content-security-policy@main
      - Jahia/contentRetrieval@main
      - Jahia/copy-to-other-languages@main
      - Jahia/core-perf-test@main
      - Jahia/core-perf-test-JMeter-WebSocketSampler@main
      - Jahia/core-perf-test-terraform@main
      - Jahia/database-connector@main
      - Jahia/default@main
      - Jahia/deleted-issues@main
      - Jahia/delivery@main
      - Jahia/dependency-track-exporter@main
      - Jahia/df-tests-api@main
      - Jahia/directive-filter@main
      - Jahia/distributed-sessions@main
      - Jahia/docker-elasticsearch@main
      - Jahia/docker-openldap@main
      - Jahia/drools@main
      - Jahia/dx-tests-specs@main
      - Jahia/ehcache@main
      - Jahia/el-spec@main
      - Jahia/elasticsearch-connector@main
      - Jahia/estool@main
      - Jahia/external-provider@main
      - Jahia/external-provider-users-groups@main
      - Jahia/facets@main
      - Jahia/felix-dev@main
      - Jahia/formidable@main
      - Jahia/forms-core@main
      - Jahia/forms-core-tests@main
      - Jahia/forms-elasticsearch-storage-tests@main
      - Jahia/forms-extended-inputs@main
      - Jahia/forms-nocss-theme@main
      - Jahia/forms-package@main
      - Jahia/forms-prefill@main
      - Jahia/forms-snippets-extension@main
      - Jahia/function-score-examples@main
      - Jahia/gemini.blueprint@main
      - Jahia/github-actions-runners@v5.17.0
      - Jahia/graphql-core@main
      - Jahia/graphql-java@v13.x-jahia
      - Jahia/graphql-java-servlet@main
      - Jahia/guest-multipart-filter@main
      - Jahia/html-filtering@main
      - Jahia/izpack@4.3
      - Jahia/jackrabbit@trunk
      - Jahia/jahia-administration@main
      - Jahia/jahia-authentication@main
      - Jahia/jahia-base-ui@main
      - Jahia/jahia-cloud-modules@main
      - Jahia/jahia-commons@main
      - Jahia/jahia-configuration@main
      - Jahia/jahia-csrf-guard@main
      - Jahia/jahia-cypress@main
      - Jahia/jahia-dashboard@main
      - Jahia/jahia-dashboard-docs@main
      - Jahia/jahia-dev-private@main
      - Jahia/jahia-developer-tools@main
      - Jahia/jahia-docker-mvn-cache@main
      - Jahia/jahia-ee@main
      - Jahia/Jahia-MF-Integ-Test-Site@main
      - Jahia/jahia-modules-action@main
      - Jahia/jahia-oauth@main
      - Jahia/jahia-pack-private@main
      - Jahia/jahia-page-composer@main
      - Jahia/jahia-private@main
      - Jahia/jahia-qa@main
      - Jahia/jahia-qa-data@main
      - Jahia/jahia-reporter@main
      - Jahia/jahia-repository-explorer@main
      - Jahia/jahia-ui-root@main
      - Jahia/jahia-user-entries@main
      - Jahia/jahia-user-feedbacks@main
      - Jahia/JahiaReleaseTool@main
      - Jahia/java-ts-bind@main
      - Jahia/javascript-components@main
      - Jahia/javascript-modules@main
      - Jahia/jcontent@main
      - Jahia/jcr-auth-provider@main
      - Jahia/jcrestapi@main
      - Jahia/jcustomer@main
      - Jahia/jcustomer-custom-event-checker@main
      - Jahia/jcustomer-perf@main
      - Jahia/jexperience@main
      - Jahia/jexperience-auth-data-mapper@main
      - Jahia/jexperience-condition-example@main
      - Jahia/jexperience-dashboards@main
      - Jahia/jexperience-forms-bridge@main
      - Jahia/jira-archives@main
      - Jahia/jquery@main
      - Jahia/json-overrides@main
      - Jahia/karaf-cellar@cellar-4.1.3-jahia-fixes
      - Jahia/keepicker@main
      - Jahia/keymaker@main
      - Jahia/kibana-dashboards-provider@main
      - Jahia/LDAP-provider@main
      - Jahia/legacy-default-components@main
      - Jahia/license-tools@main
      - Jahia/linkchecker@main
      - Jahia/lucene-solr@main
      - Jahia/luxe-jahia-demo@main
      - Jahia/macros@main
      - Jahia/maven-archetypes@main
      - Jahia/maven-release@main
      - Jahia/module-manager@main
      - Jahia/moonstone@main
      - Jahia/mvel@main
      - Jahia/news-qamf@main
      - Jahia/npm-jsx-templates-web-blue@main
      - Jahia/npm-solid-react-templateset-example@main
      - Jahia/open-source@main
      - Jahia/opencode@main
      - Jahia/org.ops4j.pax.web@main
      - Jahia/OSGi-modules-samples@main
      - Jahia/personal-api-tokens@main
      - Jahia/preview-cloud@main
      - Jahia/preview-env@main
      - Jahia/profile@main
      - Jahia/provisioning-tutorials@main
      - Jahia/qa-mf-common-utils@main
      - Jahia/qa-mf-referrer-site@main
      - Jahia/qa-mf-selenium@main
      - Jahia/qa-mf-unomi-api@main
      - Jahia/qa-mf-unomi-tracker-site@main
      - Jahia/QA-Modules@main
      - Jahia/remotepublish@main
      - Jahia/richtext-ckeditor5@main
      - Jahia/robots@main
      - Jahia/rolesmanager@main
      - Jahia/saml-authentication-valve@main
      - Jahia/sandbox@main
      - Jahia/sdk-jahia@main
      - Jahia/search@main
      - Jahia/search-ui-jahia-connector@main
      - Jahia/security-filter-tools@main
      - Jahia/selenium@main
      - Jahia/seo@main
      - Jahia/server-availability-manager@main
      - Jahia/serverSettings@main
      - Jahia/serverSettings-ee@main
      - Jahia/site-settings-publication@main
      - Jahia/site-settings-seo@main
      - Jahia/siteimprove-connector@main
      - Jahia/sitemap@main
      - Jahia/siteSettings@main
      - Jahia/skins@main
      - Jahia/spnego-authentication-valve@main
      - Jahia/spring-framework@main
      - Jahia/tags@main
      - Jahia/tasks@main
      - Jahia/templates-system@main
      - Jahia/tools@main
      - Jahia/tools-ee@main
      - Jahia/translation-globallink@main
      - Jahia/trivy-db@main
      - Jahia/update-manager@main
      - Jahia/urlrewritefilter@main
      - Jahia/userDashboard@main
      - Jahia/user-password-authentication@main
      - Jahia/visibility@main
      - Jahia/workato-unomi-connector@main
      - Jahia/workflow-extender@main      

