---
name: Spike
description: Create a spike
type: Spike
body:
  - type: textarea
    attributes:
      label: Goal
      value: "*The goal of the spike is to* "
    validations:
      required: true
  - type: textarea
    attributes:
      label: Outcome
      placeholder: Story ? POC ? Documentation ?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Notes
      placeholder: Useful information (Technical, Design)
