# Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# Syntax: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Other
description: Create a GitHub issue
title: "<title>"
labels: ["need-triage"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue
    validations:
      required: true
