# This workflow is triggered when someone create a new release in GitHub
# and checks the "This is a pre-relase" box.
name: Trigger Release creation

on:
  release:
    # `prereleased` cannot be used because draft -> prerelease does not trigger the workflow
    types: [published]

jobs:
  release-module:
    if: ${{ github.event.release.prerelease == true }}
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-release-module.yml@v2
    secrets: inherit
    with:
      primary_release_branch: $default-branch
