# Synchronize common workflows and configuration across all cloud repositories
name: Cloud - Sync. Files

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wadackel/files-sync-action@v3
        with:
          github_token: ${{ secrets.GH_ISSUES_PRS_CHORES }}
          config_file: .github/cloud-file-sync-config.yml

