name: Cloud - Sync Labels across repositories

on:
  schedule:
    - cron: '0 3 * * 0' # 3 AM Sunday
  workflow_dispatch:

jobs:
  sync-cloud-repos-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Labels across Cloud repositories
        uses: fgerthoffert/actions-sync-labels@v1.0.0
        with:
          org: jahia
          token: ${{ secrets.GH_JAHIA_CLOUD_TOKEN }}
          src_repository: .github
          filter_topics: cloud
          filter_operator: OR
